"""esquema inicial

Revision ID: efb3fa23a6de
Revises: 
Create Date: 2026-08-10 11:52:33.679725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb3fa23a6de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('office',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('office', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_office_active'), ['active'], unique=False)

    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('form_key', sa.String(length=80), nullable=False),
    sa.Column('input_type', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_key'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_sort_order'), ['sort_order'], unique=False)

    op.create_table('space',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['office_id'], ['office.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('office_id', 'name', name='uq_space_office_name')
    )
    with op.batch_alter_table('space', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_space_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_space_office_id'), ['office_id'], unique=False)

    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['office_id'], ['office.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['space.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_office_id'), ['office_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_space_id'), ['space_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_status'), ['status'], unique=False)
        batch_op.create_index('ix_order_status_created_at', ['status', 'created_at'], unique=False)

    op.create_table('order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_item_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_item_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_item_product_id'))
        batch_op.drop_index(batch_op.f('ix_order_item_order_id'))

    op.drop_table('order_item')
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index('ix_order_status_created_at')
        batch_op.drop_index(batch_op.f('ix_order_status'))
        batch_op.drop_index(batch_op.f('ix_order_space_id'))
        batch_op.drop_index(batch_op.f('ix_order_office_id'))
        batch_op.drop_index(batch_op.f('ix_order_created_at'))
        batch_op.drop_index(batch_op.f('ix_order_completed_at'))

    op.drop_table('order')
    with op.batch_alter_table('space', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_space_office_id'))
        batch_op.drop_index(batch_op.f('ix_space_active'))

    op.drop_table('space')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_sort_order'))
        batch_op.drop_index(batch_op.f('ix_product_active'))

    op.drop_table('product')
    with op.batch_alter_table('office', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_office_active'))

    op.drop_table('office')
    # ### end Alembic commands ###
