"""observacao e token de idempotencia do pedido

Revision ID: f48b783fa242
Revises: efb3fa23a6de
Create Date: 2026-10-05 17:44:00.653321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f48b783fa242'
down_revision = 'efb3fa23a6de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=280), nullable=True))
        batch_op.add_column(sa.Column('request_token', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_order_request_token'), ['request_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_request_token'))
        batch_op.drop_column('request_token')
        batch_op.drop_column('note')

    # ### end Alembic commands ###
